dotmembership/apps/members/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('dotmembership.apps.members.views',
        # Normal views
        url(r'^edit/(?P<signed_id>.+)$', 'edit', name="members-edit_member"),
        url(r'^mailing_list/$', 'mailing_list', name="members-mailing_list"),
        url(r'^confirm_join/(?P<token>\w+)$', 'confirm_join', {}, name="members-confirm_join"),
        url(r'^confirm_email/(?P<token>\w+)$', 'confirm_email_change', {}, name="members-confirm_email_change"),
        # AJAX views
        url(r'^join/$', 'join', name="members-join"),
        url(r'^send_edit_link/$', 'send_edit_link', name="members-send_edit_link"),
)

dotmembership/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'dotmembership.views.home', name='home'),
    # url(r'^dotmembership/', include('dotmembership.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^$', 'dotmembership.apps.members.views.index', name="index"),
    url(r'^admin/', include(admin.site.urls)),
    (r"^members/", include("dotmembership.apps.members.urls"))
)

dotmembership/apps/billing/models.py
# encoding: utf-8
from django.db import models
from django.db.models.signals import post_save, pre_save
from django.db.models.query import QuerySet
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy as _
from django.template.loader import render_to_string
from django.core.mail import send_mail
from django.conf import settings
from django.utils import timezone

from mailer import send_mail as mailer_send_mail

import reversion

from model_utils import Choices
from model_utils.managers import PassThroughManager
from datetime import timedelta, date, datetime

from dotmembership.apps.members.models import Member


class AnnualFeeManager(models.Manager):
    def get_fee_for_date(self, date):
        fee = self.get(start_date__lte=date, end_date__gte=date)
        return fee

    def get_active_fee(self):
        return self.get_fee_for_date(date.today())


class AnnualFee(models.Model):
    """
    Annual fee for membership.

    When a new member registers, the current annual fee
    (determined by current date, start_date and end_date) is
    used to create an invoice for the membership. Note that if
    annual fee for current date can't be found, an exception is raised.
    It's therefore admin's responsibility to ensure that a fee
    exists for any date during which a new user might register.
    Fees also should not overlap (too lazy to code any checks
    for validity...)

    When a new annual fee becomes active the billing cycle should be run,
    which generates new invoices for all existing members.
    TODO: when implemented, doc here the command name
    """
    year = models.IntegerField(_(u'vuosi'), unique=True)
    amount = models.DecimalField(max_digits=7, decimal_places=2, verbose_name=_(u"summa"))
    start_date = models.DateField(_(u'kauden alkamispäivä'))
    end_date = models.DateField(_(u'kauden loppumispäivä'))

    objects = AnnualFeeManager()

    def __unicode__(self):
        return u'{0}'.format(self.year)

reversion.register(AnnualFee)


class InvoiceQuerySet(QuerySet):
    def unpaid(self):
        """
        Returns unpaid invoices.
        """
        from .models import Invoice
        return self.exclude(status=Invoice.STATUS.paid).exclude(status=Invoice.STATUS.missed)


class Invoice(models.Model):
    STATUS = Choices(("created", _(u"luotu")),   # created, not shown/sent to member
                     ("sent", _(u"lähetetty (maksamatta)")),  # member has receiver invoice
                     ("paid", _(u"maksettu")),   # member has paid the invoide
                     ("due", _(u"erääntynyt")),  # the invoice wasn't paid before due date
                     ("missed", _(u"välistä (jätetty maksamatta)")))  # the invoice wasn't paid during year

    PAYMENT = Choices(("cash", _(u"käteinen")), ("bank", _(u"pankki")))

    member = models.ForeignKey(Member, related_name="invoices")

    status = models.CharField(_(u"tila"), choices=STATUS, default=STATUS.created, max_length=15)

    # fee that's invoiced
    fee = models.ForeignKey(AnnualFee, null=True, default=None)

    # Dates
    created = models.DateTimeField(default=timezone.now, verbose_name=_(u"luotu"))
    due_date = models.DateField(verbose_name=_(u"eräpäivä"), blank=True)
    payment_date = models.DateField(verbose_name=_(u"maksupäivä"), blank=True, null=True)

    payment_method = models.CharField(_(u"maksutapa"), choices=PAYMENT, max_length=15, blank=True, null=True)

    amount = models.DecimalField(max_digits=7, decimal_places=2, verbose_name=_(u"summa"))
    # Automatically calculated at post_save based on the id

    reference_number = models.IntegerField(_(u"viitenumero"), blank=True, null=True)

    objects = PassThroughManager.for_queryset_class(InvoiceQuerySet)()

    @property
    def paid(self):
        return self.status == self.STATUS.paid

    @property
    def for_year(self):
        return self.fee.year

    def clean(self):
        from django.core.exceptions import ValidationError
        if self.status == self.STATUS.paid and not (self.payment_date and self.payment_method):
            raise ValidationError(_(u"Syötä maksupäivä ja -tapa."))

    def send_payment_mail(self):
        subject = _(u"DOTin jäsenmaksutiedot vuodelle {0}".format(self.for_year))
        body = render_to_string("billing/mails/new_invoice.txt",
                {'invoice': self})

        # use mailer to send mail
        mailer_send_mail(subject, body, settings.DEFAULT_FROM_EMAIL, [self.member.email])

    def save(self, *args, **kwargs):
        # calculate due date
        if not self.due_date:
            self.due_date = self.created + timedelta(days=14)

        # amount from fee object
        if not self.amount:
            self.amount = self.fee.amount

        send_paid_mail = False
        if self.status == self.STATUS.paid:
            previous = Invoice.objects.get(pk=self.pk)
            if previous.status != self.STATUS.paid:
                # status has changed – send email after save
                send_paid_mail = True

        super(Invoice, self).save(*args, **kwargs)

        if send_paid_mail:
            subject = _(u"Jäsenmaksusi on kirjattu maksetuksi")
            body = render_to_string("billing/mails/invoice_paid.txt",
                                    {'invoice': self})
            send_mail(subject, body, settings.DEFAULT_FROM_EMAIL, [self.member.email])

    def __unicode__(self):
        return u"{0}, {1}".format(self.member, self.for_year)

    class Meta:
        unique_together = ("member", "fee")
        get_latest_by = "created"

reversion.register(Invoice)


def generate_invoices_for_fee(fee, dry_run=False):
    """
    Uses given fee to generate invoices for all members.
    Also sends mails about the new invoices.

    If an invoice for the given fee already exists, does nothing.
    """
    for member in Member.objects.all():
        try:
            invoice = Invoice.objects.get(member=member, amount=fee.amount, fee=fee)
        except Invoice.DoesNotExist:
            # Skip rest of the function if runnin' dry
            if dry_run:
                print u"Would generate invoice for member {0}, {1}".format(member.id, member.email)
                continue

            print u"Generating invoice for member {0}, {1}".format(member.id, member.email)
            invoice = Invoice.objects.create(member=member, amount=fee.amount, fee=fee)
            invoice.send_payment_mail()
            invoice.status = Invoice.STATUS.sent
            invoice.save()


def archive_old_unpaid_invoices(fee, dry_run=False):
    """
    TODO: document / test
    """
    # go through invoices that have not been paid
    # TODO: move the long query to InvoiceManager as a method
    for invoice in Invoice.objects.exclude(fee=fee).exclude(status=Invoice.STATUS.paid).exclude(status=Invoice.STATUS.missed):
        print u'Archivable Invoice found: status={0} fee={1} member={2}'.format(invoice.status, invoice.fee, invoice.member)
        invoice.status = Invoice.STATUS.missed
        if not dry_run:
            invoice.save()


@receiver(post_save, sender=Invoice)
def calculate_reference_number(sender, instance, created, **kwargs):
    """
    Calculates reference number for the invoice.
    """
    # TODO: this should be moved to save() as the instance is modified
    if created:
        # One-liner to calculate reference number :)
        instance.reference_number = int(str(instance.id) + str(-sum(int(x) * [7, 3, 1][i % 3] for i, x in enumerate(str(instance.id)[::-1])) % 10))
        instance.save()

dotmembership/apps/members/views.py
# encoding: utf-8
from django.shortcuts import render
from django.conf import settings
from django.http import HttpResponseRedirect
from django.core.signing import TimestampSigner, BadSignature, SignatureExpired
from django.contrib import messages

from generic_confirmation.forms import ConfirmationForm
from django_mailman.models import List

from ajaxutils.decorators import ajax
import datetime

from .forms import MemberForm, EmailForm, MemberJoinForm, MemberEmailEditForm
from .models import Member

from dotmembership.apps.billing.models import Invoice, AnnualFee


def index(request):
    """
    Index page of the member register.

    Renders a page which contains forms for joining and
    sending a self edit link
    """
    member_form = MemberJoinForm()
    email_form = EmailForm()
    current_fee = AnnualFee.objects.get_active_fee()

    return render(request, 'index.html', {
        'member_form': member_form,
        'email_form': email_form,
        'current_fee': current_fee})


def mailing_list(request):
    email_form = EmailForm()

    if request.method == "POST":
        email_form = EmailForm(request.POST)
        if email_form.is_valid():
            # Join user
            list = List(name=settings.MAILMAN_LIST_NAME,
                        password=settings.MAILMAN_LIST_PASSWORD,
                        email=settings.MAILMAN_LIST_EMAIL,
                        main_url=settings.MAILMAN_MAIN_URL,
                        encoding=settings.MAILMAN_ENCODING)
            try:
                list.subscribe(email=email_form.cleaned_data['email'])
            except Exception as e:
                # django_mailman doesn't define it's own exceptions,
                # so we must identify by the args.
                if email_form.cleaned_data['email'] in str(e):
                    messages.error(request, u"Olet jo liittynyt listallemme.")
                else:
                    # Unknown, let it bubble
                    raise
            else:
                messages.success(request, u"Onnittelut, sähköpostiosoitteesi %s on nyt liitetty listalle!" % (email_form.cleaned_data['email'],))
                return HttpResponseRedirect(request.get_full_path())
            # send email
    else:
        email_form = EmailForm()

    email_form.fields['email'].help_text = u"Syötä sähköpostiosoite, jolla haluat liittyä listalle."

    return render(request, "members/join_mailing_list.html", {'email_form': email_form})


@ajax(require_POST=True)
def join(request):
    """
    AJAX view for adding a new member to registry.
    """
    form = MemberJoinForm(request.POST)

    if form.is_valid():
        form.save()
        return {'status': 'success'}

    return {'status': 'error', 'errors': form.errors}


@ajax(require_POST=True)
def send_edit_link(request):
    """
    AJAX view for sending member edit link in email.
    """
    form = EmailForm(request.POST)

    if form.is_valid():
        try:
            member = Member.objects.get(email=form.cleaned_data["email"])
            member.send_data_and_edit_link()
        except Member.DoesNotExist:
            return {'status': 'error',
                    'errors': {'email': u"Tietokannasta ei löytynyt jäsentä antamallasi osoitteella."}}

        return {'status': 'success'}

    return {'status': 'error', 'errors': form.errors}


def confirm_join(request, token):
    """
    This view does basically the same as generic_confirmation.views.confirm_by_get,
    but as it didn't allow enough customizations to be made, the view is partia
    copied here and the behavior customized.
    """
    form = ConfirmationForm({'token': token})
    if form.is_valid() or (settings.DEBUG and request.GET.get("member_id")):
        # ConfirmationForm.save returns either the object
        # or False, if the token was not found in the database (I guess
        # this is a bug, since is_valid() should not return True if token
        # cannot be found)
        #from .models import Member
        #member = Member.objects.get(pk=1)
        if settings.DEBUG and request.GET.get("member_id"):
            member = Member.objects.get(pk=request.GET.get("member_id"))
        else:
            member = form.save()

        if member:
            fields = Member.PUBLIC_FIELDS

            # Pass form in to show the user data that was submitted
            # The invoice shown here is the one that is created in post_save
            context = {"fields": fields,
                       "member": member,
                       # This is safe, since at join there will be only one
                       # invoice anyway
                       "invoice": member.invoices.get(status=Invoice.STATUS.sent)}
            return render(request, "members/confirm_join_success.html", context)

    return render(request, "members/confirm_join_error.html")


def confirm_email_change(request, token):
    form = ConfirmationForm({'token': token})
    if form.is_valid():
        member = form.save()
        # See confirm_join - this may be buggy behavior
        if member:
            return render(request, "members/confirm_email_success.html",
                    {"member": member})

    return render(request, "members/confirm_email_error.html")


def edit(request, signed_id):
    signer = TimestampSigner()
    try:
        id = signer.unsign(signed_id, max_age=30 * 60)  # 30 minutes
        member = Member.objects.get(pk=id)
    except (BadSignature, SignatureExpired, Member.DoesNotExist):
        return render(request, "members/edit_failed.html")

    member_form = MemberForm(instance=member)
    email_form = MemberEmailEditForm(instance=member)

    if request.method == "POST":
        if "edit_member" in request.POST:
            member_form = MemberForm(request.POST, instance=member)
            if member_form.is_valid():
                member_form.save()
                messages.success(request, "Jäsentiedot tallennettu.")
                return HttpResponseRedirect(request.get_full_path())
            else:
                messages.error(request, "Korjaa jäsentiedoissa esiintyvät virheet.")
        elif "edit_email" in request.POST:
            email_form = MemberEmailEditForm(request.POST, instance=member)
            if email_form.is_valid():
                email_form.save()
                messages.success(request, u"Syöttämääsi sähköpostiosoitteeseen %s lähetettiin vahvistusviesti, \
                        josta löytyvää linkkiä sinun tulee käydä klikkaamassa vahvistaaksesi muutoksen." % email_form.cleaned_data["email"])
                return HttpResponseRedirect(request.get_full_path())
            else:
                messages.error(request, "Korjaa virheet.")

    try:
        latest_invoice = member.invoices.latest()
    except Invoice.DoesNotExist:
        latest_invoice = None

    return render(request, "members/edit.html", {"member": member,
                                                 "member_form": member_form,
                                                 "email_form": email_form,
                                                 "latest_invoice": latest_invoice,
                                                 'invoices': member.invoices.all() })

dotmembership/apps/members/templates/members/confirm_email_error.html
{% extends "base_content.html" %}
{% block title %}Sähköpostin vaihtaminen epäonnistui{% endblock %}
{% block site_content %}
<div class="row">
    <div class="span12">
        <p>Voi harmi – emme pystyneet vaihtamaan sähköpostiosoitettasi uuteen.</p>
        <p>Syynä tähän voi olla jokin seuraavista:
        <ul>
            <li><b>Päivitit sivun.</b> Vahvistuslinkki toimii vain kerran, joten tästä syystä sait virheviestin. Voit tarkistaa <a href="{% url index %}">etusivun</a> "vanha jäsen"-kohdan kautta, vaihtuiko sähköpostiosoite uuteen.</li>
            <li><b>Järjestelmässämme on bugi.</b> Mikäli et ole jo jäsen ja sait tämän virheen, ota yhteys ylläpitoon joko irkissä kanavalla #dot @ IRCNet, tai
            lähetä sähköpostia osoitteeseen dot-hallitus@list.ayy.fi</li>
        </ul>
        </p>
    </div>
</div>
{% endblock %}

dotmembership/apps/members/templates/members/confirm_email_success.html
{% extends "base_content.html" %}
{% load members_extra %}
{% block title %}Hei {{ member.first_name }}!{% endblock %}
{% block site_content %}
<div class="row">
    <div class="span12">
        <h3>Sähköpostiosoitteesi vaihdettiin</h3>
        <p>Sähköpostiosoitteesi on nyt vaihdettu osoitteeseen <b>{{ member.email }}</b>.</p>
        <p>Jatkossa sinun tulee käyttää uutta osoitetta, mikäli haluat muokata jäsentietojasi.</p>
    </div>    
</div>
{% endblock %}

dotmembership/apps/members/templates/members/confirm_join_error.html
{% extends "base_content.html" %}
{% block title %}Liittymisesi vahvistaminen epäonnistui{% endblock %}
{% block site_content %}
<div class="row">
    <div class="span12">
        <p>Voi harmi – emme pystyneet vahvistamaan liitymistäsi DOTin jäseneksi.</p>
        <p>Syynä tähän voi olla jokin seuraavista:
        <ul>
            <li><b>Päivitit sivun.</b> Vahvistuslinkki toimii vain kerran, joten tästä syystä sait virheviestin. Ei hätää! Lähetimme sinulle sähköpostiin samat tiedot,
            jotka olisit nähnyt tällä sivulla, joten et menettänyt mitään.</li>
            <li><b>Olet jo jäsen, ja klikannut linkkiä siis aiemmin.</b> Voit tarkistaa <a href="{% url index %}#old">etusivulta</a> kohdasta "vanha jäsen" jäsenyytesi tilan.</li>
            <li><b>Järjestelmässämme on bugi.</b> Mikäli et ole jo jäsen ja sait tämän virheen, ota yhteys ylläpitoon joko irkissä kanavalla #dot @ IRCNet, tai
            lähetä sähköpostia osoitteeseen dot-hallitus@list.ayy.fi</li>
        </ul>
        </p>
    </div>
</div>
{% endblock %}

dotmembership/apps/members/templates/members/confirm_join_success.html
{% extends "base_content.html" %}
{% load members_extra %}
{% block title %}Hei {{ member.first_name }}, tervetuloa jäseneksi!{% endblock %}
{% block site_content %}
<div class="row">
    <div class="span12">
        <h3>Maksa jäsenmaksu</h3>
        <p>Tämä jäsenmaksu on määrätty vuoden {{ invoice.fee.year }} vuosikokouksessa
        ja on voimassa {{ invoice.fee.start_date }} alkaen niin kauan, kunnes seuraavan
        vuosikokouksen määräämä uusi jäsenmaksu astuu voimaan.</p>
        <p>Mikäli maksoit jäsenmaksun tapahtumassa liittyessäsi käteisellä, voit ohittaa tämän vaiheen – rahastonhoitajamme kirjaa maksun maksetuksi automaattisesti.</p>
        <p>Sinulle lähetetään vielä erillinen sähköposti kun maksu on kirjattu rekisteriimme, maksoitpa käteisellä tai pankkisiirrolla.</p>
        <div class="row member-data">
            {% print_row "Saaja" "DOT ry" %}
            {% print_row "IBAN" "FI36 1309 3000 2025 49" %}
            {% print_row "BIC" "NDEAFIHH" %}
            {% print_row "Viitenumero" invoice.reference_number %}
            {% print_row "Summa" invoice.amount " euroa" %}
            {% print_row "" "<i>Mikäli maksat enemmän, tulkitaan ylimenevä osa lahjoitukseksi. :)</i>" %}
            {% print_row "Eräpäivä" invoice.due_date|date:"d.m.Y" %}
        </div>
    </div>
    <div class="span12">
        <h3>Liityit jäseneksi seuraavin tiedoin</h3>
        <p>Alla on listattu ne tiedot, jotka syötit lomakkeeseen liittyessäsi jäseneksi. Mikäli tiedoissasi on virheitä, voit muuttaa niitä <a href="{{ member.edit_link }}">tämän sivun</a> kautta.</p>
        <div class="row member-data">
            {% for field in fields %}
            <div class="span6 th">
                {{ member|getfieldname:field|capfirst }}
            </div>
            <div class="span6 td">
                {{ member|getfield:field|default:"(Tyhjä)" }}
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

dotmembership/apps/members/templates/members/div_datarow.html
<div class="span6 th">{{ th }}</div><div class="span6 td">{{ td }}</div><div class="clear"></div>

dotmembership/apps/members/templates/members/edit.html
{% extends "base_content.html" %}
{% load bootstrap %}
{% load members_extra %}
{% block title %}Hei {{ member.first_name }}!{% endblock %}
{% block site_content %}
<div class="row">
    <div class="span12">
        <h3>Viimeisin jäsenmaksu</h3>
        {% if latest_invoice.paid %}
        <p>Olet maksanut tämänhetkisen jäsenmaksun ja siis virallisesti DOTin jäsen. Tämä jäsenmaksu on voimassa {{ latest_invoice.fee.start_date }} alkaen niin kauan, kunnes seuraavan vuosikokouksen päättämä uusi jäsenmaksukausi astuu voimaan.</p>
        {% else %}
            <p>Et ole maksanut tämänhetkistä jäsenmaksua. Maksutiedot löydät alta. Tämä jäsenmaksu on voimassa {{ latest_invoice.fee.start_date }} alkaen niin kauan, kunnes seuraavan vuosikokouksen päättämä uusi jäsenmaksukausi astuu voimaan.</p>
            <div class="row member-data">
                {% print_row "Saaja" "DOT ry" %}
                {% print_row "IBAN" "FI36 1309 3000 2025 49" %}
                {% print_row "BIC" "NDEAFIHH" %}
                {% print_row "Viitenumero" latest_invoice.reference_number %}
                {% print_row "Summa" latest_invoice.amount " euroa" %}
                {% print_row "" "<i>Mikäli maksat enemmän, tulkitaan ylimenevä osa lahjoitukseksi. :)</i>" %}
                {% print_row "Eräpäivä" latest_invoice.due_date %}
            </div>
        {% endif %}
        <h3>Kaikki jäsenmaksut</h3>
        <div class="row member-data">
          {% for invoice in invoices %}
            {% print_row invoice.for_year invoice.get_status_display %}
          {% endfor %}
        </div>
        <h3>Muokkaa sähköpostiosoitettasi</h3>
        <form action="" method="POST" class="form form-horizontal">
            {% csrf_token %}
            {{ email_form|bootstrap }}
            <div class="controls">
                <button type="submit" name="edit_email" class="btn btn-large">Tallenna</button>
            </div>
        </form>
        <h3>Muokkaa jäsentietojasi</h3>
        <form action="" method="POST" class="form form-horizontal">
            {% csrf_token %}
            {{ member_form|bootstrap }}
            <div class="controls">
                <button type="submit" name="edit_member" class="btn btn-large">Tallenna</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

dotmembership/apps/members/templates/members/edit_failed.html
{% extends "base_content.html" %}
{% block title %}Tietojen muokkaaminen epäonnistui{% endblock %}
{% block site_content %}
<div class="row">
    <div class="span12">
        <h3>Linkki on vanhentunut tai epävalidi</h3>
        <p>Käyttämäsi muokkauslinkki on joko vanhentunut tai epävalidi. Tilaa uusi linkki <a href="{% url index %}">etusivulta</a>.</p>
        <p>Mikäli linkki ei toisellakaan kerralla toimi, varmista, että kopioit linkin kokonaan. Jos ongelma jatkuu, ota yhteys ylläpitoon joko sähköpostilla dot@kapsi.fi tai irkissä #dot @ IRCnet.</p>
    </div>
</div>
{% endblock %}

dotmembership/apps/members/templates/members/join_mailing_list.html
{% extends "base_content.html" %}
{% load bootstrap %}
{% block title %}Liity maililistalle!{% endblock %}
{% block site_content %}
<div class="row">
    <div class="span12">
        <p>Maililistalla dot-info@list.ayy.fi ilmoitamme kaikista tapahtumistamme. Liity listalle, jos
        olet kiinnostunut toiminnastamme! Voit myös liittyä halutessasi jäseneksi <a href="{% url index %}">rekisterin etusivun</a> kautta.</p>
        <form action="" method="POST" class="form form-horizontal">
            {% csrf_token %}
            {{ email_form|bootstrap }}
            <div class="controls">
                <button type="submit" name="edit_email" class="btn btn-large btn-warning">Klikkaa & liity!</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}